### PR TITLE
adding price list

### PR DESCRIPTION
**Pull request by marp-dev**

### CODE REVIEW

**Comment by joisig** [comment]
Hi @marp-dev, looks good, but I wonder if the table could be improved for mobile so that the leftmost column would be "sticky" and only the remaining 3 would scroll left/right? Would be a little nicer like that for responsive.

Alternatively, maybe it's easier, we could have something in the header of the second column that lets you switch between which plan you look at in that column (when on narrow screens)?

**Comment by marp-dev** [comment]
Hi @joisig I spent around 10-15 minutes placing a sticky positioning with left to the tables. This would match the first option you mentioned. Some feedback will be appreciated.

**Comment by joisig** [comment]
Hi Miguel, I made a short video for you: https://www.loom.com/share/111f7b03f8ac43e18b35deec579e31be

**Comment by marp-dev** [comment]
Hi @joisig I sent a message before but I had to remove it because I made a mess with the css while compiling the sass among other things.
I made only the first column sticky on left. by now I had to remove the bottom borders of the table.

**Comment by joisig** [comment]
Looks great now, thank you Miguel!

I am landing this now. I know my wife is thinking about a larger multi-page site so she will likely have more work for you, but that is probably still a few weeks or more in the future.

**Pull request merged**
